import webdev from "../src/assets/web-development.jpg";
import dataVisualization from "../src/assets/datavisualization.jpg";
import businessAnalytics from "../src/assets/businessanalytics.jpg";
import communication from "../src/assets/communication.jpg";
import cyberSecurity from "../src/assets/cyberSecurity.jpg";
export const coursesData = [
    {
      id: 1,
      title: "Introduction to Web Development",
      description: "Learn the fundamentals of web development, including HTML, CSS, and JavaScript.",
      category: "Web Development",
      image: webdev,
      price: "₹499",
      lecturer: "Dr. Angela Yu",
      ch1:"Introduction",
      ch1d:"Get started with the basics.",
      ch1ep1:"Episode 1: Welcome to the Course",
      ch1ep1d:"Learn about the course structure and objectives.",
      ch1ep2:"Episode 2: Getting Started",
      ch1ep2d:"Set up your development environment.",
      ch1ep3:"",
      ch2:"Core Concepts",
      ch2d:"Dive into the key topics.",
      ch2ep1:"Episode 1: Fundamentals of React",
      ch2ep1d:"Learn the core concepts of React.",
      ch2ep2:"Episode 2: State Management",
      ch2ep2d:"Explore state management in React.",
      ch2ep3:"Episode 3: Routing and Navigation",
      ch2ep3d:"Learn how to handle routing in your React app.",
      ch3:"Advanced Topics",
      ch3d:"Explore more advanced React concepts.",
      ch3ep1:"Episode 1: Performance Optimization",
      ch3ep1d:"Learn techniques to optimize your React app.",
      ch3ep2:"Episode 2: Testing and Debugging",
      ch3ep2d:"Explore testing and debugging strategies for React.",
      ch3ep3:"Episode 3: Deployment and Hosting",
      ch3ep3d:"Learn how to deploy your React app.",
    },
    {
      id: 2,
      title: "Mastering Data Visualization 2024",
      description: "Discover the power of data visualization and learn how to create stunning charts and graphs.",
      category: "Data Science",
      image: dataVisualization,
      price: "₹499",
      lecturer: "Jose Portilla, Pierian Training",
      ch1:"Introduction",
      ch1d:" Get started with the basics of data visualization.",
      ch1ep1:"Episode 1: Welcome to Data Visualization",
      ch1ep1d:"An overview of the course structure and objectives.",
      ch1ep2:"Episode 2: Importance of Data Visualization",
      ch1ep2d:"Understand why data visualization is crucial in today's data-driven world.",
      ch1ep3:"Episode 3: Tools and Technologies",
      ch1ep3d:"Introduction to the tools and technologies used in data visualization.",
      ch2:"Core Concepts",
      ch2d:"Dive into the key topics of data visualization.",
      ch2ep1:"Episode 1: Types of Data Visualizations",
      ch2ep1d:" Explore different types of data visualizations and their applications. ",
      ch2ep2:"Episode 2: Principles of Effective Visualization ",
      ch2ep2d:"Learn the principles that make data visualizations effective and impactful.",
      ch2ep3:"Episode 3: Data Preparation and Cleaning",
      ch2ep3d:"Understand the importance of data preparation and cleaning before visualization.",
      ch3:"Advanced Topics",
      ch3d:"Explore more advanced concepts in data visualization.",
      ch3ep1:"Episode 1: Interactive Visualizations ",
      ch3ep1d:"Description: Learn how to create interactive visualizations that engage users.",
      ch3ep2:"Episode 2: Advanced Chart Types  ",
      ch3ep2d:"Description: Dive into advanced chart types like heatmaps, tree maps, and network diagrams.",
      ch3ep3:"Episode 3: Data Storytelling      ",
      ch3ep3d:"Understand how to tell compelling stories with your data visualizations.",
    },
    {
      id: 3,
      title: "Become a Business Analytics Expert",
      description: "Dive into the world of business analytics and learn the latest strategies to grow your business.",
      category: "Business Analytics",
      image: businessAnalytics,
      price: "₹499",
      lecturer: "Start Tech Academy",
      ch1:"Introduction",
      ch1d:"Get started with the basics.",
      ch1ep1:"Episode 1: Overview of Business Analytics      ",
      ch1ep1d:"Understand what business analytics is and its importance in the modern business landscape",
      ch1ep2:"Episode 2: The Role of Data in Business      ",
      ch1ep2d:"Explore how data is used in businesses to drive decision-making and strategic planning.",
      ch1ep3:"Episode 3: Tools and Technologies in Business Analytics      ",
      ch1ep3d:"Get introduced to the essential tools and technologies used in business analytics.",
      ch2:"Core Concepts",
      ch2d:"Dive into the key topics.",
      ch2ep1:"Episode 1: Descriptive Analytics      ",
      ch2ep1d:"Learn how descriptive analytics helps in understanding past performance and identifying patterns.",
      ch2ep2:"Episode 2: Predictive Analytics      ",
      ch2ep2d:"Discover how predictive analytics is used to forecast future trends and behaviors.",
      ch2ep3:"Episode 3: Prescriptive Analytics      ",
      ch2ep3d:"Understand how prescriptive analytics provides recommendations for decision-making based on data.",
      ch3:"Advanced Topics",
      ch3d:"Explore more advanced React concepts.",
      ch3ep1:"Episode 1: Advanced Data Modeling Techniques      ",
      ch3ep1d:" Dive into complex data modeling techniques used for deeper insights and analysis.",
      ch3ep2:"Episode 2: Machine Learning in Business Analytics      ",
      ch3ep2d:" Explore the application of machine learning algorithms to business analytics for better predictions and automation.",
      ch3ep3:"Episode 3: Data Privacy and Ethical Considerations",
      ch3ep3d:"Learn about the importance of data privacy and ethics in business analytics practices.",
    },
    {
      id: 4,
      title: "Mastering Communication Skills",
      description: "Learn the essential skills and techniques to become an effective communicator.",
      category: "Communication",
      image: communication,
      price: "₹499",
      lecturer: "Sushmita Dutta, Ash Akshay Goel",
      ch1:"Introduction",
      ch1d:"Get started with the basics.",
      ch1ep1:"Episode 1: The Importance of Communication",
      ch1ep1d:"Understand why effective communication is crucial in both personal and professional settings..",
      ch1ep2:"Episode 2: Basic Communication Models",
      ch1ep2d:" Learn the foundational models that explain how communication works.",
      ch1ep3:"Episode 3: Overcoming Communication Barriers",
      ch1ep3d:" Identify and overcome common obstacles to effective communication.",
      ch2:"Core Concepts",
      ch2d:"Dive into the key topics.",
      ch2ep1:"Episode 1: Verbal Communication Techniques",
      ch2ep1d:" Explore key techniques to improve your spoken communication.      ",
      ch2ep2:"Episode 2: Non-Verbal Communication",
      ch2ep2d:"Understand the power of body language and facial expressions.",
      ch2ep3:"Episode 3: Listening Skills",
      ch2ep3d:" Learn how to become an active and empathetic listener.",
      ch3:"Advanced Topics",
      ch3d:"Explore more advanced React concepts.",
      ch3ep1:"Episode 1: Persuasive Communication",
      ch3ep1d:"Discover strategies to influence and persuade others effectively.",
      ch3ep2:"Episode 2: Communicating in Conflict",
      ch3ep2d:"Master techniques for resolving conflicts through effective communication.",
      ch3ep3:"Episode 3: Cross-Cultural Communication",
      ch3ep3d:"Develop skills to communicate effectively in a multicultural environment.",
    },
    {
      id: 5,
      title: "Advanced Cybersecurity Techniques",
      description: "Explore the latest cybersecurity strategies and protect your digital assets.",
      category: "IT Certifications",
      image: cyberSecurity,
      price: "₹499",
      lecturer: "Logix Academy",
      ch1:"Introduction",
      ch1d:" Get started with the basics of cybersecurity, setting the foundation for more advanced topics",
      ch1ep1:"Episode 1: Welcome to CyberSecurity      ",
      ch1ep1d:"Introduction to the course structure and objectives",
      ch1ep2:"Episode 2: CyberSecurity Fundamentals      ",
      ch1ep2d:"Overview of key cybersecurity principles and concepts.",
      ch1ep3:"Episode 3: Setting Up Your Environment      ",
      ch1ep3d:"How to set up a secure environment for cybersecurity practices.",
      ch2:"Core Concepts",
      ch2d:" Dive into the essential topics that form the backbone of advanced cybersecurity.",
      ch2ep1:"Episode 1: Understanding Threats and Vulnerabilities      ",
      ch2ep1d:"Explore various cyber threats and system vulnerabilities.",
      ch2ep2:"Episode 2: Network Security Principles      ",
      ch2ep2d:"Key strategies and practices for securing networks.",
      ch2ep3:"Episode 3: Cryptography Basics      ",
      ch2ep3d:" Introduction to cryptographic methods and their applications in security.",
      ch3:"Advanced Topics",
      ch3d:"Explore advanced concepts and techniques in cybersecurity to enhance your skills.",
      ch3ep1:"Episode 1: Advanced Attack Techniques      ",
      ch3ep1d:" In-depth analysis of sophisticated attack methods used by cybercriminals.",
      ch3ep2:"Episode 2: Episode 2: Incident Response and Management      ",
      ch3ep2d:"Effective strategies for responding to and managing cybersecurity incidents.",
      ch3ep3:"Episode 3: Cyber Forensics      ",
      ch3ep3d:"Description: Techniques for investigating and analyzing cyber incidents to gather evidence.",
    },
  ]